stages:
  bathymetry:
    cmd: uv run notebooks/rijkswaterstaat/1_bathymetrie.py
    deps:
      - notebooks/rijkswaterstaat/1_bathymetrie.py
    outs:
      - data/Rijkswaterstaat/verwerkt/bathymetrie
    frozen: true
  peelbeheerst:
    foreach:
      delfland: Delfland
      amstel_gooi_en_vecht: AmstelGooienVecht
      hollands_noorderkwartier: HollandsNoorderkwartier
      hollandse_delta: HollandseDelta
      rijnland: Rijnland
      rivierenland: Rivierenland
      scheldestromen: Scheldestromen
      schieland_en_de_krimpenerwaard: SchielandendeKrimpenerwaard
      wetterskip_fryslan: WetterskipFryslan
      zuiderzeeland: Zuiderzeeland
    do:
      cmd:
        - uv run src/peilbeheerst_model/Parametrize/${item}_parametrize.py
      deps:
        - src/peilbeheerst_model/Parametrize/${item}_parametrize.py
      outs:
        - data/${item}/modellen/${item}_parameterized
  rijkswaterstaat:
    cmd:
      - uv run notebooks/rijkswaterstaat/2_basins.py
      - uv run notebooks/rijkswaterstaat/3_netwerk.py
      - uv run notebooks/rijkswaterstaat/4_kunstwerken.py
      - uv run notebooks/rijkswaterstaat/5_model_netwerk.py
      - uv run notebooks/rijkswaterstaat/6_model_sturing.py
      - uv run notebooks/rijkswaterstaat/7_model_onttrekkingen.py
      - uv run notebooks/rijkswaterstaat/8a_update_state.py
      - uv run notebooks/rijkswaterstaat/8b_update_bc.py
    deps:
      - data/Rijkswaterstaat/verwerkt/bathymetrie
      - data/Rijkswaterstaat/modellen/rwzi
      - notebooks/rijkswaterstaat
    outs:
      - data/Rijkswaterstaat/modellen/hws_transient
      - data/Rijkswaterstaat/verwerkt/netwerk.gpkg
  parameterized:
    foreach:
      aa_en_maas: AaenMaas
      brabantse_delta: BrabantseDelta
      de_dommel: DeDommel
      drents_overijsselse_delta: DrentsOverijsselseDelta
      hunze_en_aas: HunzeenAas
      limburg: Limburg
      noorderzijlvest: Noorderzijlvest
      rijn_en_ijssel: RijnenIJssel
      stichtse_rijnlanden: StichtseRijnlanden
      vallei_en_veluwe: ValleienVeluwe
      vechtstromen: Vechtstromen
    do:
      cmd:
        - uv run notebooks/${key}/_preprocess_profielen.py
        - uv run notebooks/${key}/01_fix_model.py
        - uv run notebooks/${key}/02_prepare_model.py
        - uv run notebooks/${key}/03_parameterize_model.py
      deps:
        - notebooks/${key}/_preprocess_profielen.py
        - notebooks/${key}/01_fix_model.py
        - notebooks/${key}/02_prepare_model.py
        - notebooks/${key}/03_parameterize_model.py
      outs:
        - data/${item}/modellen/${item}_parameterized_model
  bergend:
    foreach:
      aa_en_maas: AaenMaas
      brabantse_delta: BrabantseDelta
      de_dommel: DeDommel
      drents_overijsselse_delta: DrentsOverijsselseDelta
      hunze_en_aas: HunzeenAas
      limburg: Limburg
      noorderzijlvest: Noorderzijlvest
      rijn_en_ijssel: RijnenIJssel
      stichtse_rijnlanden: StichtseRijnlanden
      vallei_en_veluwe: ValleienVeluwe
      vechtstromen: Vechtstromen
    do:
      cmd:
        - uv run notebooks/${key}/04_add_full_control.py
        - uv run notebooks/05_add_bergend.py ${item}
      deps:
        - notebooks/${key}/04_add_full_control.py
        - notebooks/05_add_bergend.py
        - data/${item}/modellen/${item}_parameterized_model
      outs:
        - data/${item}/modellen/${item}_bergend_model
  dynamic:
    foreach:
      aa_en_maas: AaenMaas
      brabantse_delta: BrabantseDelta
      de_dommel: DeDommel
      drents_overijsselse_delta: DrentsOverijsselseDelta
      hunze_en_aas: HunzeenAas
      limburg: Limburg
      noorderzijlvest: Noorderzijlvest
      rijn_en_ijssel: RijnenIJssel
      stichtse_rijnlanden: StichtseRijnlanden
      vallei_en_veluwe: ValleienVeluwe
      vechtstromen: Vechtstromen
    do:
      cmd: uv run notebooks/07_add_dynamic_forcing.py ${item}
      deps:
        - notebooks/07_add_dynamic_forcing.py
        - data/${item}/modellen/${item}_bergend_model
        - data/Rijkswaterstaat/modellen/rwzi
      outs:
        - data/${item}/modellen/${item}_dynamic_model
  rwzi:
    cmd: uv run notebooks/create_rwzi_model.py
    deps:
      - notebooks/create_rwzi_model.py
    outs:
      - data/Rijkswaterstaat/modellen/rwzi
  samenvoegen:
    cmd: uv run notebooks/samenvoegen_modellen.py
    deps:
      - notebooks/samenvoegen_modellen.py
      - data/Rijkswaterstaat/modellen/hws_transient
      # - data/HollandsNoorderkwartier/modellen/HollandsNoorderkwartier_parameterized
      # - data/AmstelGooienVecht/modellen/AmstelGooienVecht_parameterized
      # - data/Delfland/modellen/Delfland_parameterized
      # - data/Rijnland/modellen/Rijnland_parameterized
      # - data/Rivierenland/modellen/Rivierenland_parameterized
      # - data/Scheldestromen/modellen/Scheldestromen_parameterized
      # - data/SchielandendeKrimpenerwaard/modellen/SchielandendeKrimpenerwaard_parameterized
      # - data/WetterskipFryslan/modellen/WetterskipFryslan_parameterized
      # - data/Zuiderzeeland/modellen/Zuiderzeeland_parameterized
      # - data/HollandseDelta/modellen/HollandseDelta_parameterized
      - data/AaenMaas/modellen/AaenMaas_dynamic_model
      - data/BrabantseDelta/modellen/BrabantseDelta_dynamic_model
      - data/DeDommel/modellen/DeDommel_dynamic_model
      - data/DrentsOverijsselseDelta/modellen/DrentsOverijsselseDelta_dynamic_model
      - data/HunzeenAas/modellen/HunzeenAas_dynamic_model
      - data/Limburg/modellen/Limburg_dynamic_model
      - data/Noorderzijlvest/modellen/Noorderzijlvest_dynamic_model
      - data/RijnenIJssel/modellen/RijnenIJssel_dynamic_model
      - data/StichtseRijnlanden/modellen/StichtseRijnlanden_dynamic_model
      - data/ValleienVeluwe/modellen/ValleienVeluwe_dynamic_model
      - data/Vechtstromen/modellen/Vechtstromen_dynamic_model
    outs:
      - data/Rijkswaterstaat/modellen/lhm_parts
  koppelen:
    cmd: uv run notebooks/koppelen_modellen.py
    deps:
      - notebooks/koppelen_modellen.py
      - data/Rijkswaterstaat/modellen/lhm_parts
      - data/Rijkswaterstaat/verwerkt/netwerk.gpkg
    outs:
      - data/Rijkswaterstaat/modellen/lhm_coupled
