stages:
  bathymetry:
    cmd: uv run notebooks/rijkswaterstaat/1_bathymetrie.py
    deps:
      - notebooks/rijkswaterstaat/1_bathymetrie.py
    outs:
      - data/Rijkswaterstaat/verwerkt/bathymetrie
    frozen: true
  rijkswaterstaat:
    cmd:
      - uv run notebooks/rijkswaterstaat/2_basins.py
      - uv run notebooks/rijkswaterstaat/3_netwerk.py
      - uv run notebooks/rijkswaterstaat/4_kunstwerken.py
      - uv run notebooks/rijkswaterstaat/5_model_netwerk.py
      - uv run notebooks/rijkswaterstaat/6_model_sturing.py
      - uv run notebooks/rijkswaterstaat/7_model_onttrekkingen.py
      - uv run notebooks/rijkswaterstaat/8a_update_state.py
      - uv run notebooks/rijkswaterstaat/8b_update_bc.py
    deps:
      - data/Rijkswaterstaat/verwerkt/bathymetrie
      - data/Rijkswaterstaat/modellen/rwzi
      - notebooks/rijkswaterstaat
    outs:
      - data/Rijkswaterstaat/modellen/hws_transient
  brabantse_delta:
    cmd:
      - uv run notebooks/brabantse_delta/_preprocess_profielen.py
      - uv run notebooks/brabantse_delta/01_fix_model.py
      - uv run notebooks/brabantse_delta/02_prepare_model.py
      - uv run notebooks/brabantse_delta/03_parameterize_model.py
      - uv run notebooks/brabantse_delta/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py BrabantseDelta
      - uv run notebooks/07_add_dynamic_forcing.py BrabantseDelta
    deps:
      - notebooks/brabantse_delta
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/BrabantseDelta/modellen/BrabantseDelta_dynamic_model
  rwzi:
    cmd: uv run notebooks/create_rwzi_model.py
    deps:
      - notebooks/create_rwzi_model.py
    outs:
      - data/Rijkswaterstaat/modellen/rwzi
  samenvoegen:
    cmd: uv run notebooks/samenvoegen_modellen.py
    deps:
      - data/Rijkswaterstaat/modellen/hws_transient
      # - data/HollandsNoorderkwartier/modellen/HollandsNoorderkwartier_parameterized
      # - data/AmstelGooienVecht/modellen/AmstelGooienVecht_parameterized
      # - data/Delfland/modellen/Delfland_parameterized
      # - data/Rijnland/modellen/Rijnland_parameterized
      # - data/Rivierenland/modellen/Rivierenland_parameterized
      # - data/Scheldestromen/modellen/Scheldestromen_parameterized
      # - data/SchielandendeKrimpenerwaard/modellen/SchielandendeKrimpenerwaard_parameterized
      # - data/WetterskipFryslan/modellen/WetterskipFryslan_parameterized
      # - data/Zuiderzeeland/modellen/Zuiderzeeland_parameterized
      - data/AaenMaas/modellen/AaenMaas_dynamic_model
      # - data/BrabantseDelta/modellen/BrabantseDelta_dynamic_model
      # - data/DeDommel/modellen/DeDommel_dynamic_model
      # - data/DrentsOverijsselseDelta/modellen/DrentsOverijsselseDelta_dynamic_model
      # - data/HunzeenAas/modellen/HunzeenAas_dynamic_model
      # - data/Limburg/modellen/Limburg_dynamic_model
      # - data/Noorderzijlvest/modellen/Noorderzijlvest_dynamic_model
      # - data/RijnenIJssel/modellen/RijnenIJssel_dynamic_model
      # - data/StichtseRijnlanden/modellen/StichtseRijnlanden_dynamic_model
      # - data/ValleienVeluwe/modellen/ValleienVeluwe_dynamic_model
      # - data/Vechtstromen/modellen/Vechtstromen_dynamic_model
      # - data/HollandseDelta/modellen/HollandseDelta_parameterized
    outs:
      - data/Rijkswaterstaat/modellen/lhm_parts
  koppelen:
    cmd: uv run notebooks/koppelen_modellen.py
    deps:
      - data/Rijkswaterstaat/modellen/lhm_parts
    outs:
      - data/Rijkswaterstaat/modellen/lhm_coupled
  aa_en_maas:
    cmd:
      - uv run notebooks/aa_en_maas/01_fix_model.py
      - uv run notebooks/aa_en_maas/02_prepare_model.py
      - uv run notebooks/aa_en_maas/03_parameterize_model.py
      - uv run notebooks/aa_en_maas/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py AaenMaas
      - uv run notebooks/07_add_dynamic_forcing.py AaenMaas
    deps:
      - notebooks/aa_en_maas
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/AaenMaas/modellen/AaenMaas_dynamic_model
  noorderzijlvest:
    cmd:
      - uv run notebooks/noorderzijlvest/01_fix_model.py
      - uv run notebooks/noorderzijlvest/02_prepare_model.py
      - uv run notebooks/noorderzijlvest/03_parameterize_model.py
      - uv run notebooks/noorderzijlvest/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py Noorderzijlvest
      - uv run notebooks/07_add_dynamic_forcing.py Noorderzijlvest
    deps:
      - notebooks/noorderzijlvest
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/Noorderzijlvest/modellen/Noorderzijlvest_dynamic_model
  stichtse_rijnlanden:
    cmd:
      - uv run notebooks/stichtse_rijnlanden/01_fix_model.py
      - uv run notebooks/stichtse_rijnlanden/02_prepare_model.py
      - uv run notebooks/stichtse_rijnlanden/03_parameterize_model.py
      - uv run notebooks/stichtse_rijnlanden/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py StichtseRijnlanden
      - uv run notebooks/07_add_dynamic_forcing.py StichtseRijnlanden
    deps:
      - notebooks/stichtse_rijnlanden
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/StichtseRijnlanden/modellen/StichtseRijnlanden_dynamic_model
  drents_overijsselse_delta:
    cmd:
      - uv run notebooks/drents_overijsselse_delta/01_fix_model.py
      - uv run notebooks/drents_overijsselse_delta/02_prepare_model.py
      - uv run notebooks/drents_overijsselse_delta/03_parameterize_model.py
      - uv run notebooks/drents_overijsselse_delta/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py DrentsOverijsselseDelta
      - uv run notebooks/07_add_dynamic_forcing.py DrentsOverijsselseDelta
    deps:
      - notebooks/drents_overijsselse_delta
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/DrentsOverijsselseDelta/modellen/DrentsOverijsselseDelta_dynamic_model
  rijn_en_ijssel:
    cmd:
      - uv run notebooks/rijn_en_ijssel/01_fix_model.py
      - uv run notebooks/rijn_en_ijssel/02_prepare_model.py
      - uv run notebooks/rijn_en_ijssel/03_parameterize_model.py
      - uv run notebooks/rijn_en_ijssel/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py RijnenIJssel
      - uv run notebooks/07_add_dynamic_forcing.py RijnenIJssel
    deps:
      - notebooks/rijn_en_ijssel
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/RijnenIJssel/modellen/RijnenIJssel_dynamic_model
  vechtstromen:
    cmd:
      - uv run notebooks/vechtstromen/01_fix_model.py
      - uv run notebooks/vechtstromen/02_prepare_model.py
      - uv run notebooks/vechtstromen/03_parameterize_model.py
      - uv run notebooks/vechtstromen/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py Vechtstromen
      - uv run notebooks/07_add_dynamic_forcing.py Vechtstromen
    deps:
      - notebooks/vechtstromen
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/Vechtstromen/modellen/Vechtstromen_dynamic_model
  de_dommel:
    cmd:
      - uv run notebooks/de_dommel/01_fix_model.py
      - uv run notebooks/de_dommel/02_prepare_model.py
      - uv run notebooks/de_dommel/03_parameterize_model.py
      - uv run notebooks/de_dommel/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py DeDommel
      - uv run notebooks/07_add_dynamic_forcing.py DeDommel
    deps:
      - notebooks/de_dommel
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/DeDommel/modellen/DeDommel_dynamic_model
  vallei_en_veluwe:
    cmd:
      - uv run notebooks/vallei_en_veluwe/01_fix_model.py
      - uv run notebooks/vallei_en_veluwe/02_prepare_model.py
      - uv run notebooks/vallei_en_veluwe/03_parameterize_model.py
      - uv run notebooks/vallei_en_veluwe/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py ValleienVeluwe
      - uv run notebooks/07_add_dynamic_forcing.py ValleienVeluwe
    deps:
      - notebooks/vallei_en_veluwe
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/ValleienVeluwe/modellen/ValleienVeluwe_dynamic_model
  limburg:
    cmd:
      - uv run notebooks/limburg/_preprocess_profielen.py
      - uv run notebooks/limburg/01_fix_model.py
      - uv run notebooks/limburg/02_prepare_model.py
      - uv run notebooks/limburg/03_parameterize_model.py
      - uv run notebooks/limburg/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py Limburg
      - uv run notebooks/07_add_dynamic_forcing.py Limburg
    deps:
      - notebooks/limburg
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/Limburg/modellen/Limburg_dynamic_model
  hunze_en_aas:
    cmd:
      - uv run notebooks/hunze_en_aas/01_fix_model.py
      - uv run notebooks/hunze_en_aas/02_prepare_model.py
      - uv run notebooks/hunze_en_aas/03_parameterize_model.py
      - uv run notebooks/hunze_en_aas/04_add_full_control.py
      - uv run notebooks/05_add_bergend.py HunzeenAas
      - uv run notebooks/07_add_dynamic_forcing.py HunzeenAas
    deps:
      - notebooks/hunze_en_aas
      - data/Rijkswaterstaat/modellen/rwzi
    outs:
      - data/HunzeenAas/modellen/HunzeenAas_dynamic_model
