# ribasim environment with some extra goodies to work in NL-context
name: ribasim

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - build
  - datamodel-code-generator
  - geopandas
  - jupyterlab
  - matplotlib
  - mypy
  - openpyxl
  - pandas
  - pandas-stubs
  - pip
  - pre-commit
  - pyarrow
  - pydantic>=2
  - pyogrio
  - pytest
  - pytest-cov
  - python>=3.9
  - quartodoc
  - rasterstats
  - ruff
  - shapely>=2.0
  - tomli
  - tomli-w
  - typing-extensions>=4.6
  - twine
  - xarray
  - xmipy
