[project]
name = "Ribasim-NL"
version = "0.1.0"
description = "Ribasim water resources modeling in the Netherlands"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

[tasks]
# Installation
install-hydamo = "pip install --no-deps --editable src/hydamo"
install-ribasim_nl = "pip install --no-deps --editable src/ribasim_nl"
install-quartodoc = "pip install quartodoc"
install-pre-commit = "pre-commit install"
install-without-pre-commit = { depends_on = [
    "install-hydamo",
	"install-ribasim_nl",
    "install-quartodoc",
] }
install = { depends_on = [
    "install-without-pre-commit",
    "install-pre-commit",
] }
# Lint
mypy-hydamo = "mypy --ignore-missing-imports src/hydamo"
pre-commit = "pre-commit run --all-files"
lint = { depends_on = [
    "pre-commit",
    "mypy-hydamo",
] }
# Test
test-hydamo = "pytest --numprocesses=auto --basetemp=src/hydamo/tests/temp src/hydamo/tests"
test-ribasim_nl = "pytest --numprocesses=auto --basetemp=src/hydamo/tests/temp src/ribasim_nl/tests"
test-hydamo-cov = "pytest --numprocesses=auto --cov=hydamo --cov-report=xml src/hydamo/tests"
tests = { depends_on = [
    "lint",
    "test-hydamo",
] }

[dependencies]
python = ">=3.9"
pandas = "<2.1"
geopandas = "0.14.0.*"
fiona = "1.9.4.*"
tomli = "2.0.1.*"
shapely = ">=2"
pydantic = "~=1.0"
pandera = "!=0.16.0"
pyarrow = "13.0.0.*"
pyogrio = "0.6.0.*"
ribasim = "0.5.0.*"
rasterstats = "0.19.0.*"
tomli-w = "1.0.0.*"
matplotlib = "3.8.0.*"
# dev
ruff = "0.0.292.*"
black = "23.9.1.*"
pytest = "7.4.2.*"
pytest-cov = "4.1.0.*"
pytest-xdist = "3.3.1.*"
pip = "23.2.1.*"
pre-commit = "3.4.0.*"
ipykernel = "6.25.2.*"
mypy = "1.5.1.*"
requests = "2.31.0.*"
types-requests = "2.31.0.10.*"
