[project]
name = "Ribasim-NL"
version = "0.1.0"
description = "Ribasim water resources modeling in the Netherlands"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

[tasks]
# Installation
install-hydamo = "pip install --no-deps --editable src/hydamo"
install-ribasim_nl = "pip install --no-deps --editable src/ribasim_nl"
install-pre-commit = "pre-commit install"
install-without-pre-commit = { depends_on = [
    "install-hydamo",
    "install-ribasim_nl",
] }
install = { depends_on = [
    "install-without-pre-commit",
    "install-pre-commit",
] }
# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" }
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends_on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends_on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends_on = [
    "quartodoc-build",
] }
docs = { depends_on = ["build-julia-docs", "quarto-preview"] }
# Lint
mypy-hydamo = "mypy --ignore-missing-imports src/hydamo"
pre-commit = "pre-commit run --all-files"
lint = { depends_on = [
    "pre-commit",
    "mypy-hydamo",
] }
# Test
test-hydamo = "pytest --numprocesses=auto --basetemp=src/hydamo/tests/temp src/hydamo/tests"
test-ribasim_nl = "pytest --numprocesses=auto --basetemp=src/ribasim_nl/tests/temp src/ribasim_nl/tests"
test-hydamo-cov = "pytest --numprocesses=auto --cov=hydamo --cov-report=xml --cov-report=term-missing src/hydamo/tests"
test-ribasim_nl-cov = "pytest --numprocesses=auto --cov=ribasim_nl --cov-report=xml --cov-report=term-missing src/ribasim_nl/tests"
tests = { depends_on = [
    "lint",
    "test-hydamo",
    "test-ribasim_nl",
] }

[dependencies]
fiona = "*"
geocube = "*"
geopandas = "*"
ipykernel = "*"
jupyterlab = "*"
matplotlib = "*"
mypy = "*"
openpyxl = "*"
pandas = "*"
pip = "*"
pre-commit = "*"
pyarrow = "*"
pydantic = ">=2.0"
pyogrio = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
python = ">=3.9"
quarto = "*"
quartodoc = "*"
rasterstats = "*"
requests = "*"
ribasim = "==2024.3.0"
ruff = "*"
shapely = ">=2"
tomli = "*"
tomli-w = "*"
types-requests = "*"
