[project]
name = "Ribasim-NL"
version = "0.1.0"
description = "Ribasim water resources modeling in the Netherlands"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

[tasks]
# Installation
install = "pre-commit install"
# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" }
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends-on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends-on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends-on = [
    "quartodoc-build",
] }
docs = { depends-on = ["build-julia-docs", "quarto-preview"] }
# Lint
mypy-hydamo = "mypy --ignore-missing-imports src/hydamo"
pre-commit = "pre-commit run --all-files"
lint = { depends-on = ["pre-commit", "mypy-hydamo"] }
# Test
test-hydamo = "pytest --numprocesses=auto --basetemp=src/hydamo/tests/temp src/hydamo/tests"
test-ribasim_nl = "pytest --numprocesses=auto --basetemp=src/ribasim_nl/tests/temp src/ribasim_nl/tests"
test-peilbeheerst_model = "pytest --numprocesses=auto --basetemp=src/peilbeheerst_model/tests/temp src/peilbeheerst_model/tests"
test-hydamo-cov = "pytest --numprocesses=auto --cov=hydamo --cov-report=xml --cov-report=term-missing src/hydamo/tests"
test-ribasim_nl-cov = "pytest --numprocesses=auto --cov=ribasim_nl --cov-report=xml --cov-report=term-missing src/ribasim_nl/tests"
test-peilbeheerst_model-cov = "pytest --numprocesses=auto --cov=peilbeheerst_model --cov-report=xml --cov-report=term-missing src/peilbeheerst_model/tests"
tests = { depends-on = ["lint", "test-hydamo", "test-ribasim_nl"] }

[dependencies]
bokeh = ">=3.0"
contextily = "*"
fiona = "*"
geocube = "*"
geopandas = "*"
ipykernel = "*"
jupyterlab = "*"
matplotlib = "*"
mypy = "*"
networkx = ">=3.4"
openpyxl = "*"
pandas = "*"
pandas-stubs = "*"
pip = "*"
pre-commit = "*"
pyarrow = "*"
pydantic = ">=2"
pyogrio = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
python = ">=3.11"
quarto = "*"
quartodoc = "*"
rasterstats = "*"
requests = "*"
ruff = "*"
shapely = ">=2"
tomli = "*"
tomli-w = "*"
tqdm = "*"
types-requests = "*"
xlwings = "*"
xugrid = "*"

[pypi-dependencies]
bokeh_helpers = { path = "src/bokeh_helpers", editable = true }
hydamo = { path = "src/hydamo", editable = true }
peilbeheerst_model = { path = "src/peilbeheerst_model", editable = true }
ribasim_nl = { path = "src/ribasim_nl", editable = true }

[feature.dev.pypi-dependencies]
ribasim = { path = "../Ribasim/python/ribasim", editable = true }

[feature.prod.dependencies]
ribasim = "==2025.2.0"

[environments]
default = ["prod"]
dev = ["dev"]
