/** Node and link styling of the Ribasim QGIS plugin, see `python/ribasim/ribasim/styles` in the Ribasim repository. */

export type Color = [number, number, number];

// Icons generated by `utils/write_node_icons.py` in the Ribasim repository
const NODE_ICON_URL = "https://s3.deltares.nl/ribasim/doc-image/node-icons/";

/** Node types with an icon, and the icon fill color as fallback for drawing circles. */
export const NODE_STYLES: Record<string, Color> = {
  Basin: [0, 114, 178],
  ManningResistance: [240, 228, 66],
  LinearResistance: [0, 158, 115],
  FlowBoundary: [255, 127, 0],
  LevelBoundary: [255, 255, 255],
  TabulatedRatingCurve: [204, 121, 167],
  Pump: [153, 153, 153],
  Outlet: [213, 94, 0],
  UserDemand: [228, 26, 28],
  LevelDemand: [230, 159, 0],
  FlowDemand: [34, 139, 34],
  DiscreteControl: [152, 78, 163],
  PidControl: [0, 100, 0],
  ContinuousControl: [153, 153, 153],
  Terminal: [0, 0, 0],
  Junction: [0, 0, 0],
  Observation: [0, 0, 0],
};

export interface LinkStyle {
  color: Color;
  dashed: boolean;
}

export const LINK_STYLES: Record<string, LinkStyle> = {
  flow: { color: [54, 144, 192], dashed: false },
  control: { color: [128, 128, 128], dashed: false },
  listen: { color: [128, 128, 128], dashed: true },
  observation: { color: [0, 0, 0], dashed: true },
};
export const DEFAULT_LINK_STYLE: LinkStyle = { color: [0, 0, 0], dashed: false };
export const DEFAULT_NODE_COLOR: Color = [128, 128, 128];

/** QGIS sizes in mm, at 96 DPI */
const MM = 96 / 25.4;
// Smaller than the 6.6 mm in QGIS, where nodes are typically viewed less densely
export const NODE_ICON_SIZE_PX = 4.2 * MM;
export const LINK_WIDTH_PX = 0.5 * MM;
export const ARROW_SIZE_PX = 3 * MM;

/** PNG icon for use in HTML. */
export function nodeIconPng(nodeType: string): string | null {
  return nodeType in NODE_STYLES ? `${NODE_ICON_URL}png/${nodeType}.png` : null;
}

export const ARROW_ICON = "arrow";
const ATLAS_ICON_PX = 64;

export interface IconAtlas {
  /** PNG data URL */
  atlas: string;
  mapping: Record<string, { x: number; y: number; width: number; height: number; mask: boolean }>;
}

async function loadSvg(nodeType: string): Promise<HTMLImageElement> {
  const image = new Image(ATLAS_ICON_PX, ATLAS_ICON_PX);
  // Without CORS the canvas becomes tainted and cannot be exported as the atlas
  image.crossOrigin = "anonymous";
  image.src = `${NODE_ICON_URL}svg/${nodeType}.svg`;
  await image.decode();
  return image;
}

/** Rasterize the node icons and a link arrow into one atlas; node types whose icon fails to load are left out. */
export async function loadIconAtlas(): Promise<IconAtlas> {
  const nodeTypes = Object.keys(NODE_STYLES);
  const results = await Promise.allSettled(nodeTypes.map(loadSvg));
  const atlas = document.createElement("canvas");
  atlas.width = ATLAS_ICON_PX * (nodeTypes.length + 1);
  atlas.height = ATLAS_ICON_PX;
  const context = atlas.getContext("2d")!;
  const mapping: IconAtlas["mapping"] = {};
  results.forEach((result, i) => {
    if (result.status !== "fulfilled") return;
    const x = i * ATLAS_ICON_PX;
    context.drawImage(result.value, x, 0, ATLAS_ICON_PX, ATLAS_ICON_PX);
    mapping[nodeTypes[i]] = { x, y: 0, width: ATLAS_ICON_PX, height: ATLAS_ICON_PX, mask: false };
  });

  // QGIS "filled_arrowhead", pointing east, colored per link type through the mask
  const x = nodeTypes.length * ATLAS_ICON_PX;
  const s = ATLAS_ICON_PX;
  context.fillStyle = "#fff";
  context.beginPath();
  context.moveTo(x + s, s / 2);
  context.lineTo(x, 0);
  context.lineTo(x, s);
  context.closePath();
  context.fill();
  mapping[ARROW_ICON] = { x, y: 0, width: s, height: s, mask: true };
  return { atlas: atlas.toDataURL("image/png"), mapping };
}
