# https://www.aquo.nl/index.php/Imwa_sim_1.0/doc/codelijst/waterbeheerder
waterbeheercode = {
    "HollandseDelta": 40,
    "Zuiderzeeland": 37,
    "HollandsNoorderkwartier": 12,
    "Rivierenland": 9,
    "Delfland": 15,
    "AaenMaas": 38,
    "WetterskipFryslan": 2,
    "Noorderzijlvest": 34,
    "BrabantseDelta": 25,
    "HunzeenAas": 33,
    "Scheldestromen": 42,
    "Vechtstromen": 44,
    "RijnenIJssel": 7,
    "ValleienVeluwe": 43,
    "SchielandendeKrimpenerwaard": 39,
    "StichtseRijnlanden": 14,
    "DeDommel": 27,
    "Limburg": 60,
    "DrentsOverijsselseDelta": 59,
    "Rijnland": 13,
    "AmstelGooienVecht": 11,
    "Rijkswaterstaat": 80,
}
