waterschap_data = {
    "AmstelGooienVecht": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/AmstelGooienVecht/AGV.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/AmstelGooienVecht/agv_crossings_v05.gpkg",
            "search_radius_structure": 60,
        },
    },
    "Delfland": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Delfland/Delfland.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Delfland/delfland_crossings_v08.gpkg",
            "search_radius_structure": 60,
        },
    },
    "HHNK": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/HHNK/Noorderkwartier.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/HHNK/hhnk_crossings_v26.gpkg",
            "search_radius_structure": 60,
        },
    },
    "HHSK": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/HHSK/HHSK.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/HHSK/hhsk_crossings_v04.gpkg",
            "search_radius_structure": 300,
        },
    },
    "Hollandse Delta": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Hollandse_Delta/HD.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Hollandse_Delta/hd_crossings_v06.gpkg",
            "search_radius_structure": 300,
        },
    },
    "Rijnland": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Rijnland/Rijnland.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Rijnland/rijnland_crossings_v04.gpkg",
            "search_radius_structure": 60,
        },
    },
    "Scheldestromen": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Scheldestromen/Scheldestromen.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Scheldestromen/scheldestromen_crossings_v02.gpkg",
            "search_radius_structure": 60,
        },
    },
    "WSRL": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/WSRL/WSRL.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/WSRL/wsrl_crossings_v06.gpkg",
            "search_radius_structure": 60,
        },
    },
    "Wetterskip": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Wetterskip/Wetterskip.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Wetterskip/wetterskip_crossings_v06.gpkg",
            "search_radius_structure": 60,
        },
    },
    "Zuiderzeeland": {
        "find_crossings_with_peilgebieden": {"filterlayer": "duikersifonhevel", "group_stacked": True},
        "init": {
            "agg_peilgebieden_column": "code",
            "agg_peilgebieden_layer": "aggregation_area",
            "gpkg_path": "../../../../Data_postprocessed/Waterschappen/Zuiderzeeland/Zuiderzeeland.gpkg",
            "krw_column_id": "owmident",
            "krw_column_name": "owmnaam",
            "krw_min_overlap": 0.025,
            "krw_path": "../../../../Data_overig/KRW/KRW_lichamen_per_waterschap.gpkg",
            "output_path": "../../../../Data_crossings/Zuiderzeeland/zzl_crossings_v05.gpkg",
            "search_radius_structure": 60,
        },
    },
}
