---
title: "Level controlled"
---

Workflow for deriving level controlled (peilbeheerst) regional models.
All code can be found under [`src/peilbeheerst_model`](https://github.com/Deltares/Ribasim-NL/tree/main/src/peilbeheerst_model).
The paths below are relative to this path.

1. Run the preprocessing scripts. One script per water board, path: `peilbeheerst_model/preprocess_data/`
2. Run the postprocessing script. One script per water board, path: `peilbeheerst_model/postprocess_data/`
3. Run the crossings script. One script, path: `01_parse_crossings.ipynb`. Moving to one script per water board under `peilbeheerst_model/parse_crossings/`.
4. Run shortest paths scripts. One script per water board, path: `Shortest_path/`
5. Run crossings to Ribasim script. One script, all water boards are below each other, path: `02_crossings_to_ribasim_notebook.ipynb`. Moving to one script per water board under `peilbeheerst_model/crossings_to_ribasim/`.
6. Run parametrize scripts. One script per water board, for now only Amstel, Gooi en Vecht (AGV), path: `Parametrize/AmstelGooienVecht_parametrize.ipynb`

We originally had more parametrize scripts, but because so much has changed I have now saved these in our backup.
We will only use these to see if there were any additional manual adjustments.
For the rest, it follows the same workflow as `AmstelGooienVecht_parametrize.ipynb`.

Finally: step 1 started with a clear script per water board.
During the process of 1.5 years, these scripts have become increasingly larger and more confusing, whereby not every line is needed anymore.
For now, there is no priority to clean this up, partly because this is a major risk that the data will (unintentionally) change, which will change the networks and the feedback forms can no longer be used.
