name: Update Pixi lockfile
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    # At 03:00 on day 3 of the month
    - cron: "0 3 3 * *"
  # on demand
  workflow_dispatch:
jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ribasim-NL
        uses: actions/checkout@v4
        with:
          path: Ribasim-NL
      # Ribasim needs to be checked out next to this repo even for the prod environment
      - name: Checkout Ribasim
        uses: actions/checkout@v4
        with:
          repository: Deltares/Ribasim
          path: Ribasim
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          manifest-path: Ribasim-NL/pixi.toml
          pixi-version: "latest"
          run-install: false
      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
        working-directory: Ribasim-NL
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_PR_PAT }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          path: Ribasim-NL
          body-path: Ribasim-NL/diff.md
          branch: update/pixi-lock
          base: main
          delete-branch: true
          add-paths: pixi.lock
