name: Prek auto update
on:
  schedule:
    # At 03:00 on day 3 of the month
    - cron: "0 3 3 * *"
  # on demand

  workflow_dispatch:
permissions:
  contents: read
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version: "0.11.7"
      - name: Install the project
        run: uv sync --locked
      - name: Update hook revisions
        run: |
          uv run prek auto-update
      - name: Run prek on all files
        run: |
          uv run prek run --all-files
        continue-on-error: true
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.CI_PR_PAT }}
          branch: update/pre-commit
          title: Update git hooks
          commit-message: "Update git hooks"
          author: "GitHub <noreply@github.com>"
          delete-branch: true
