name: Python Lint
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Ribasim-NL
        uses: actions/checkout@v4
        with:
          path: Ribasim-NL

      # Ribasim needs to be checked out next to this repo even for the prod environment
      - name: Checkout Ribasim
        uses: actions/checkout@v4
        with:
          repository: Deltares/Ribasim
          path: Ribasim

      - uses: prefix-dev/setup-pixi@v0.8.7
        with:
          manifest-path: Ribasim-NL/pixi.toml
          pixi-version: "latest"

      - name: Run mypy on hydamo
        working-directory: Ribasim-NL
        run: pixi run mypy-hydamo
