name: Python Tests
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  merge_group:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test:
    name: Python ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: "latest"
      - name: Run tests
        run: |
          pixi run pytest --numprocesses=auto --basetemp=src/hydamo/tests/temp src/hydamo/tests
          pixi run pytest --numprocesses=auto --basetemp=src/ribasim_nl/tests/temp src/ribasim_nl/tests
          pixi run pytest scripts/test_edit_toml.py
        env:
          RIBASIM_NL_CLOUD_PASS: ${{ secrets.RIBASIM_NL_CLOUD_PASS }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
