name: Python Tests
on:
  push:
    branches: [main]
    paths-ignore: [".teamcity/**"]
    tags: ["*"]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Python ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x86
    steps:
      - name: Checkout Ribasim-NL
        uses: actions/checkout@v4
        with:
          path: Ribasim-NL

      # Ribasim needs to be checked out next to this repo even for the prod environment
      - name: Checkout Ribasim
        uses: actions/checkout@v4
        with:
          repository: Deltares/Ribasim
          path: Ribasim

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: Ribasim-NL/pixi.toml
          pixi-version: "latest"
          log-level: "v"

      - name: Run tests
        working-directory: Ribasim-NL
        run: pixi run test-hydamo
        env:
          RIBASIM_NL_CLOUD_PASS: ${{ secrets.RIBASIM_NL_CLOUD_PASS }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
